# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzle', '0003_auto_20161014_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together=set([('user', 'number')]),
        ),
    ]
